/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function sum(a: number, b: number): number
export interface FileMetadata {
  path: string
  content?: string
  size?: number
  modified?: string
  error?: string
}
export declare function readFileInfo(name: string): FileMetadata
export declare function readFileAsync(path: string): Promise<Buffer>
